import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter, EB_Garamond } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500"], // Add lighter weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      signInFallbackRedirectUrl="/dashboard"
      signUpFallbackRedirectUrl="/dashboard"
    >
    <html lang="en" className={`${inter.variable} ${ebGaramond.variable}`}>
      <body
        className="font-sans antialiased"
      >
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
